# Generated by Django 3.1.4 on 2020-12-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='emotions',
            field=models.CharField(default='Neutral', max_length=15),
        ),
    ]
