# Generated by Django 3.1.4 on 2020-12-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_info_emotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='emotions',
        ),
    ]
