# Generated by Django 3.1.4 on 2020-12-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_info_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='username',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
