# Generated by Django 3.1.4 on 2020-12-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_info_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='emotion',
            field=models.CharField(default='Neutral', max_length=50),
        ),
    ]
