# Generated by Django 3.1.4 on 2020-12-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
