# Generated by Django 3.1.4 on 2020-12-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201208_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='image',
        ),
    ]
